services:
  db:
    image: "postgres:17"
    container_name: "lorx_db"
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=lorx_dev
    volumes:
      - /var/lib/postgresql/data
