name: Deploy

# Run only after the CI workflow (build.yml -> name: Elixir CI) completes successfully
# and only for the 'release' branch.
on:
  workflow_run:
    workflows: ["Elixir CI"]
    types: [completed]

env:
  CONTAINER_REGISTRY_URL: ghcr.io
  IMAGE_NAME: emadb/lorx
  HEAD_BRANCH: ${{ github.event.workflow_run.head_branch }}

jobs:
  # Guard job to ensure we only proceed on success AND correct branch
  precheck:
    runs-on: ubuntu-latest
    if: >-
      ${{ github.event.workflow_run.conclusion == 'success' && github.event.workflow_run.head_branch == 'release' }}
    outputs:
      proceed: ${{ steps.set.outputs.proceed }}
    steps:
      - id: set
        run: echo "proceed=true" >> $GITHUB_OUTPUT
  setup:
    if: ${{ needs.precheck.outputs.proceed == 'true' }}
    needs: precheck
    runs-on: [self-hosted]
    outputs:
      version: ${{ steps.configure.outputs.version }}
    steps:
      - id: configure
        name: Configure environment
        run: |
          VERSION=`date '+%Y.%m%d.%H%M'`
          echo "version=$VERSION" >> $GITHUB_OUTPUT

  package:
    if: ${{ needs.precheck.outputs.proceed == 'true' }}
    runs-on: [self-hosted]
    needs: [precheck, setup]
    env:
      VERSION: ${{ needs.setup.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3
        with:
          platforms: linux/arm64
      - name: Build and push core image
        uses: docker/build-push-action@v4
        with:
          context: .
          file: Dockerfile
          tags: "${{ env.CONTAINER_REGISTRY_URL }}/${{ env.IMAGE_NAME }}:${{ env.VERSION }}"
          push: true

  tag-and-release:
    if: ${{ needs.precheck.outputs.proceed == 'true' }}
    runs-on: [self-hosted]
    needs: [precheck, setup]
    env:
      VERSION: ${{ needs.setup.outputs.version }}
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3
      - name: Create tag and release
        run: gh release create ${{ env.VERSION }} --title ${{ env.VERSION }} --target ${{ env.HEAD_BRANCH }} docker-compose-prod.yml
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  deploy:
    if: ${{ needs.precheck.outputs.proceed == 'true' }}
    runs-on: [self-hosted]
    needs: [precheck, setup, package, tag-and-release]
    environment: prod
    env:
      VERSION: ${{ needs.setup.outputs.version }}
    steps:
      - name: Download artifacts
        run: gh release download ${{ env.VERSION }} -R ${{ github.REPOSITORY }} --clobber
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
      - name: Setup infrastructure (if needed) and deploy artifacts
        run: |
          docker stack config --compose-file docker-compose-prod.yml > final.docker-compose.yml
          docker stack deploy --compose-file final.docker-compose.yml --resolve-image always --with-registry-auth lorx
        env:
          DATABASE_URL: postgresql://postgres:postgres@postgresql/lorx_dev
          SECRET_KEY_BAS: =xhSxmI3mCFHOfGwkc483qhI1dkXSrw3yh6XniKW88HmcoDSAUcYaW7gObmfz8Occ
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          ENV_NAME: ${{ vars.ENV_NAME }}
          DEVICE_POLLING_INTERVAL: ${{ vars.DEVICE_POLLING_INTERVAL }}
          SAVING_INTERVAL: ${{ vars.SAVING_INTERVAL }}
